["meta"]
identifier = "ch.so.agi.av.dm01_so"
title = "Amtliche Vermessung (DM01 CH + DXF/Geobau)"
description = """
Datenbereitstellung gemäss Bundesmodell "DM01AVCH24LV95D" inklusive GEOBAU-DXF (SN 612 020).
<br/><br/>
Die amtliche Vermessung hält als Bestandteil des Grundbuches die genauen Grenzverläufe der Grundstücke fest und schafft damit die Basis zur Sicherung des Grundeigentums. Nebst den aktuellen Grundstücksgrenzen sind in den Daten der amtlichen Vermessung auch weitere Objekte wie Gebäude, Strassen, Gebäudeadressen, Fixpunkte usw. abgebildet.
"""
keywords = "Grundbuch"
synonyms = "AV,Vermessung,Kataster,Parzellarvermessung"
model = "DM01AVSO24LV95"
owner = "ch.so.agi"
servicer = "ch.so.agi"
licence = "https://files.geo.so.ch/nutzungsbedingungen.html"
formats = ["ITF"]

["config"]
printClassDescription = false

