apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gretl-secrets
  labels:
    app: gretl-platform
stringData:
  ORG_GRADLE_PROJECT_dbUserEdit: myusername1
  ORG_GRADLE_PROJECT_dbPwdEdit: mypassword1
  ORG_GRADLE_PROJECT_dbUserPub: myusername2
  ORG_GRADLE_PROJECT_dbPwdPub: mypassword2
